# numpy 

In [70]:
import numpy as np

# array() it is a numpy method used to create an array in python

"""
syntax :-

np.array(value) -> value it can be list/tuple/nested list/nested tuple
    
"""

arr = np.array([1,2,3,4,5])
print(arr,type(arr))

[1 2 3 4 5] <class 'numpy.ndarray'>


In [3]:
arr = np.array([1,2,3,4,True])
print(arr,type(arr))

[1 2 3 4 1] <class 'numpy.ndarray'>


In [4]:
arr = np.array([1,2,3,4,"Hi"])
print(arr,type(arr))

['1' '2' '3' '4' 'Hi'] <class 'numpy.ndarray'>


In [5]:
arr = np.array([1,2,3,4,5.5,40],dtype=int)
arr

array([ 1,  2,  3,  4,  5, 40])

In [6]:
arr = np.array(['hi','hello','hellooooo'])
arr

array(['hi', 'hello', 'hellooooo'], dtype='<U9')

In [7]:
arr = np.array(['hi', 'hello', 'hellooooo'], dtype='<U5')
arr

array(['hi', 'hello', 'hello'], dtype='<U5')

In [8]:
arr = np.array([1,2,3,4])
arr+2

array([3, 4, 5, 6])

# Built in Methods

In [9]:
# normal loop
for i in range(1,11):
    print(i) # float value is not possible to pass

res = list(range(1,11,1))
res

1
2
3
4
5
6
7
8
9
10


[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

## using arange()

In [10]:
np.arange(1,11)
np.arange(1,11,0.5)

array([ 1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5,  5. ,  5.5,  6. ,
        6.5,  7. ,  7.5,  8. ,  8.5,  9. ,  9.5, 10. , 10.5])

## linspace()

### which is used to split equally space between start and end values
### it will includes end value no need to add extra for neglecting
### in this case we can't pass only end value like range we need to pass both start and end step is optional by default 50

In [11]:
np.linspace(1,10,4)

# start 1 and equal space required 4
# so 1-4, 4-7, 7-10

array([ 1.,  4.,  7., 10.])


### by default equally split is 50 creates an empty space value

In [12]:
np.linspace(1,10)

array([ 1.        ,  1.18367347,  1.36734694,  1.55102041,  1.73469388,
        1.91836735,  2.10204082,  2.28571429,  2.46938776,  2.65306122,
        2.83673469,  3.02040816,  3.20408163,  3.3877551 ,  3.57142857,
        3.75510204,  3.93877551,  4.12244898,  4.30612245,  4.48979592,
        4.67346939,  4.85714286,  5.04081633,  5.2244898 ,  5.40816327,
        5.59183673,  5.7755102 ,  5.95918367,  6.14285714,  6.32653061,
        6.51020408,  6.69387755,  6.87755102,  7.06122449,  7.24489796,
        7.42857143,  7.6122449 ,  7.79591837,  7.97959184,  8.16326531,
        8.34693878,  8.53061224,  8.71428571,  8.89795918,  9.08163265,
        9.26530612,  9.44897959,  9.63265306,  9.81632653, 10.        ])

## shape

### this shape is not built in method it is an attribute
### ---> it is used to identify the shape of array which is consider as table rows and columns

### array shape returns shape of rows and columns

In [13]:
arr = np.array([[1,2,3,4],[1,2,3,4],[1,2,3,4]])
print(arr.shape)

(3, 4)


In [14]:
arr1 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
print(arr1.shape)

(1, 3, 4)


## ndim() --> it returns dimension of an array like 1-D, 2-D, 3-D like that

In [15]:
arr.ndim

2

In [16]:
arr1.ndim

3

## dtype --> it returns of type of array

In [17]:
arr.dtype

dtype('int32')

In [18]:
arr1 = np.array([[[1,2,3,4],[1,2,3,4],[1,2,3,4]]])
arr1

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

## size --> which is used to define the size of array

In [19]:
arr1.size

12

## slicing 

### 1-D slicing

In [20]:
arr = np.array([1,2,3,4,5])
arr[0:2] # --> if we directly call then output will be array([1, 2])
print(arr[0:2]) # --> it we returns in the form of list

[1 2]


### 2-D slicing

In [21]:
arr = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(arr[1:3,1:3])

[[5 6]
 [8 9]]


In [22]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
print(arr)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


In [23]:
print(arr[1:3,1:4])

[[ 7  8  9]
 [12 13 14]]


In [24]:
print(arr[2:5,0:3])

[[11 12 13]
 [16 17 18]
 [21 22 23]]


In [25]:
print(arr[1:3,4:])

[[10]
 [15]]


In [26]:
print(arr[3:,3:])

[[19 20]
 [24 25]]


## flattern() vs ravel()

In [27]:
arr = np.array([[1,2,3,4,5],[6,7,8,9,10],[11,12,13,14,15],[16,17,18,19,20],[21,22,23,24,25]])
flat_arr = arr.flatten() # converts arr into 1D and returns new array
print(flat_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [28]:
ravel_arr = arr.ravel()
print(ravel_arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24
 25]


In [29]:
# updated values in flattern and ravel
flat_arr[0] = 100
ravel_arr[1] = 1000
print("Flattern:",flat_arr)
print("ravel:",ravel_arr)

Flattern: [100   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17  18
  19  20  21  22  23  24  25]
ravel: [   1 1000    3    4    5    6    7    8    9   10   11   12   13   14
   15   16   17   18   19   20   21   22   23   24   25]


## flatern doesn't affect origninal but ravel affects original

### flatern creates a copy and doesn't affect original
### ravel affects the original array because it taking of refernce of original array like normal reference in list so it affects the original

In [30]:
print("original array:") # here ravel only affects the original like normal reference in list
print(arr)

original array:
[[   1 1000    3    4    5]
 [   6    7    8    9   10]
 [  11   12   13   14   15]
 [  16   17   18   19   20]
 [  21   22   23   24   25]]


In [31]:
l = [1,2,3,4]
l1 = l
l1[0] = 100
print(l)

[100, 2, 3, 4]


## reshape() vs resize()

### it won't affect original dimension if we take creates a variable and stores it into then we get updated dimension

In [32]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
print(arr)
arr.shape

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


(3, 4)

In [33]:
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [34]:
print(arr.reshape(1,12))

[[ 1  2  3  4  5  6  7  8  9 10 11 12]]


In [35]:
print(arr.reshape(12,1))

[[ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]]


In [36]:
print(arr.reshape(6,2))

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [37]:
print(arr.reshape(2,6))

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


In [38]:
print(arr.reshape(4,3))

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [39]:
print(arr.reshape(3,4))

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]


## resize()

### reshape returns new value
### resize it returns none

In [40]:
arr = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12]])
new_arr = arr.resize(4,3)
print(new_arr)
print(arr)

None
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


## sum()

### syntax:-
### np.sum(arr) => returns value
### mean()
### np.mean(arr) => returns value
### np.std(arr) => returns value

In [41]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr1 = np.array([[1,2,3,],[4,5,6],[7,8,9]])

In [42]:
arr1

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [43]:
np.sum(arr)

45

## axis which is used to add column wise axis = 1 means cloumn axis = 0 means row wise

In [44]:
np.sum(arr1,axis=0) # axis which is used to add column wise axis = 0 means row axis = 1 means column wise

array([12, 15, 18])

In [45]:
np.sum(arr1,axis=1)

array([ 6, 15, 24])

In [46]:
np.mean(arr)

5.0

In [47]:
np.mean(arr1)

5.0

## sort()

In [48]:
arr = np.array([1,4,5,2,3,6,8,7,9])
arr1 = np.array([[10,1,5],[20,200,1],[6,3,2]])
np.sort(arr)

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [49]:
np.sort(arr1)

array([[  1,   5,  10],
       [  1,  20, 200],
       [  2,   3,   6]])

In [50]:
print(arr[::-1])

[9 7 8 6 3 2 5 4 1]


In [51]:
print(arr[:1])

[1]


In [52]:
print(arr1[:])

[[ 10   1   5]
 [ 20 200   1]
 [  6   3   2]]


In [53]:
print(arr1[:,::-1])

[[  5   1  10]
 [  1 200  20]
 [  2   3   6]]


In [54]:
print(np.sort(arr1))

[[  1   5  10]
 [  1  20 200]
 [  2   3   6]]


In [55]:
import copy
arr = np.array([1,2,3,4,5,6,7,8,9])
arr_c = copy.copy(arr)
print(arr_c)

[1 2 3 4 5 6 7 8 9]


In [56]:
arr[0] = 100
print(arr)

[100   2   3   4   5   6   7   8   9]


In [57]:
print(arr_c)

[1 2 3 4 5 6 7 8 9]


In [58]:
arr_c[1] = 1000
print(arr_c)

[   1 1000    3    4    5    6    7    8    9]


In [59]:
print(arr)

[100   2   3   4   5   6   7   8   9]


## Shallow and Deepcopy in numpy

In [60]:
import copy

arr_2d = np.array([[1,2],[3,4]])
# arr_2d[0][0] = 1000
print(arr_2d)

[[1 2]
 [3 4]]


In [61]:
arr_c = copy.copy(arr_2d)
print(arr_c)

[[1 2]
 [3 4]]


In [62]:
arr_2d[0][0] = 1000
print(arr_2d)

[[1000    2]
 [   3    4]]


In [63]:
print(arr_c)

[[1 2]
 [3 4]]


In [64]:
arr_dp = copy.deepcopy(arr_2d)
print(arr_2d)

[[1000    2]
 [   3    4]]


In [65]:
arr_2d[0][0] = 2000
print(arr_2d)

[[2000    2]
 [   3    4]]


In [66]:
print(arr_dp)

[[1000    2]
 [   3    4]]


## difference between view and copy

## view is like shallow copy
## copy is like deep copy

## min() and max()

In [67]:
arr = np.array([1,2,3,4,5])
print(min(arr))

1


In [68]:
print(max(arr))

5


In [69]:
arr= np.array([[10,2],[4,1]])
arr1 = np.array([1,2,3,4,5,6,7])
print(np.max(arr))
print(np.max(arr1))
np.min(arr1)

10
7


1